### ISSUE TITLE
cli hangs on some slim files

### ISSUE THREAD

**Issue by joshblour** [phrase/slimkeyfy#1]
I've come across cases where slimkeyfy hangs with specific slim files.

It always happens with the same files so there must be something in the markup that's tripping it up.

Here's an example of one of the file contents:
````slim
#faq-box.w-hidden-small.w-hidden-tiny.back-faq-box data-ix="new-interaction"
  .u-marginbottom-20.fontsize-small.fontweight-semibold Perguntas Frequentes
  ul.w-list-unstyled
    li.list-question.fontsize-smaller.alt-link  Como eu apoio este projeto?
    li.list-answer.u-marginbottom-20.fontsize-smaller Primeiro, escolha o valor e a recompensa desejados. Depois é só clicar em 'Revisar e realizar pagamento' que redirecionaremos você para a próxima página para concluir o seu pagamento.

    li.list-question.fontsize-smaller.alt-link  Quando o pagamento é efetivado?
    li.list-answer.u-marginbottom-20.fontsize-smaller Se você pagou com cartão de crédito, a confirmação deverá ser no mesmo dia. Se foi com boleto, em até 4 dias úteis.

    li.list-question.fontsize-smaller.alt-link  E se o projeto não atingir a meta?
    li.list-answer.u-marginbottom-20.fontsize-smaller Nesse caso, você recebe de volta 100% do que pagou através de um reembolso.

    li.list-question.fontsize-smaller.alt-link  Se o projeto for financiado, como eu recebo minha recompensa?
    li.list-answer.u-marginbottom-20.fontsize-smaller Quando sua recompensa estiver pronta, #{link_to @project.user.display_name, user_path(@project.user)} vai entrar em contato com você para combinar a entrega.
````

and the command which I'm running:
````
 slimkeyfy app/views/catarse_bootstrap/projects/contributions/_faq_box.html.slim pt contributions.pt.yml
````

i suspect it has something to do with the very first line, which I believe is valid slim syntax

**Comment by sacry-dyn** [comment]
Hi,

I will have a look at this. Thank you for posting :)

Regards,
Matthias

**Comment by joshblour** [comment]
thank YOU GUYS for the amazing library! saved me tons of work.

also, do you know of a way to scan files recursively? I end up using **/* then **/**/* then **/**/**/* etc...

**Comment by sacry-dyn** [comment]
Hi josh,

I found the issue in a html matching regex. It was badly constructed and I fixed it. Your given example  should work now. Also for recursively going through everything there is the -r option like this:

slimkeyfy -r path/to/dir en path/to/en.yml

I hope this helps!

Regards,
Matthias
