### ISSUE TITLE
Using translator

### ISSUE THREAD

**Issue by ACPK** [phrase/slimkeyfy#11]
@aleksey @phraseapp-vincent - I'm working on an open-source app that it is in Portuguese and converting it to be used by English speakers. How do I use the translator before it creates the i18n call?

**Comment by sacry-dyn** [comment]
Hi @ACPK ,

could you clarify what you mean by "translator"? Do you mean the yandex translator?

https://github.com/phrase/slimkeyfy#i18n-for-keys-addition

What do you mean by i18n call and before? 

The process is first to internationalize with slimkeyfy e.g. extract translations from views/code and move it into the yaml referenced by key (this would be Portuguese). Second use our service PhraseApp to translate into the languages you like.

Regards,
Matthias

**Comment by sacry-dyn** [comment]
I will close this for now. If anything comes up feel free to reopen.
